In [ ]:
Library == Package, Module(단일.py)의 상위 개념

In [13]:
%%writefile module_example.py 

#쥬피터노트북 내장 기능 파일 생성

def print_something() :
    print('HelloWorld')
    
def sum_nums(num1, num2):
    return num1 + num2

Overwriting module_example.py


In [16]:
import module_example

module_example.print_something()

HelloWorld


In [ ]:
라이브러리 설치 명령어
cmd혹은 아나콘다 프롬프트
pip install 라이브러리 이름
conda install 라이브러리 이름

In [21]:
import mldl #라이브러리 설치 X

ModuleNotFoundError: No module named 'mldl'

In [18]:
import numpy # import 라이브러리 이름

In [19]:
a = numpy.array([1,2,3])
a

array([1, 2, 3])

In [23]:
import numpy as np #import 라이브러리 이름 as 별명

In [24]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [25]:
from numpy import array, ndarray #from 라이브러리 이름 import 함수이름
#비추천 위험함
a = array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
데이터 분석을 위해 자주 사용되는 파이썬 패키지/모듈
numpy 수치형 자료 계산 및 연산 np
pandas 정형 데이터 전처리 및 분석 pd
matplotlib 데이터 차트 시각화 plt
seaborn 보다 개선된 데이터 시각화 sns
beautifulsoup4 웹 데이터 추출(web scraping) from bs4 import...
nltk 자연어 데이터 전처리 import nltk
scikit-learn 전통적인 머신러닝 알고리즘 from sklearn import...

In [28]:
import random # 외장 함수

x = random.random()
x

0.1787104280108046

In [30]:
x = random.randint(1, 100)
x

58