In [64]:
import numpy as np

In [65]:
# 1차원 배열
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [66]:
type(arr1) # n-Dimensional array

numpy.ndarray

In [67]:
arr1.dtype #배열 내 데이터 의 타입

dtype('int64')

In [68]:
# 2차원 배열
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2.shape # 모양, 배열의 형태 (각 차원의 크기) 2행 3열

(2, 3)

In [70]:
arr2.ndim # 배열의 차원 수 n-차원

2

In [71]:
a = np.zeros((2, 2)) #영행렬
a

array([[0., 0.],
       [0., 0.]])

In [72]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [73]:
a = np.eye(3) # Identitry matrix 항등행렬
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
a = np.random.random((2, 2))
a

array([[0.86677826, 0.08691782],
       [0.11098655, 0.04102114]])

In [75]:
arr = np.random.randint(1, 100, size = (5, 5)) #random int
arr

array([[16, 90, 93, 64,  1],
       [93, 75, 37, 30, 71],
       [67, 74, 26, 20, 60],
       [88, 59, 71, 61, 79],
       [33, 38,  9, 44, 76]])

In [76]:
arr = np.random.random(10)
arr

array([0.10819154, 0.05734404, 0.96055464, 0.09294582, 0.46317466,
       0.55309314, 0.75314109, 0.28111921, 0.81375953, 0.73176151])

In [77]:
arr.sort()
arr

array([0.05734404, 0.09294582, 0.10819154, 0.28111921, 0.46317466,
       0.55309314, 0.73176151, 0.75314109, 0.81375953, 0.96055464])

In [78]:
arr[0]

0.05734404052711317

In [79]:
arr[2:5]

array([0.10819154, 0.28111921, 0.46317466])

In [80]:
arr[0:5:3]

array([0.05734404, 0.28111921])

In [81]:
arr[::-1] # 역순으로 출력~!

array([0.96055464, 0.81375953, 0.75314109, 0.73176151, 0.55309314,
       0.46317466, 0.28111921, 0.10819154, 0.09294582, 0.05734404])

In [82]:
# Array operators
arr = np.arange(9) # array of range
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
arr = arr.reshape(3,3) # 다시 모양을 변경
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
arr.sum()

36

In [85]:
arr.min()

0

In [86]:
arr.max()

8

In [87]:
arr.max(axis=0) #열방향 max

array([6, 7, 8])

In [88]:
arr.max(axis=1) #행빙향

array([2, 5, 8])

In [89]:
arr.mean(axis=1) #행방향 mean

array([1., 4., 7.])

In [90]:
np.median(arr, axis=1)

array([1., 4., 7.])

In [91]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
# 주대각 원소(대각선상에 있는 원소)를 추출하거나
# 대각 행렬(정사각행렬의 주대각 성분 이외의 모든 성분이 0인 행렬)을 생성
diag = np.diag(arr)
diag

array([0, 4, 8])

In [94]:
diag_mat = np.diag(diag)
diag_mat

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [95]:
# Matrix operators
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
C = np.array([[1,2],[3,4],[5,6]])
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
A + B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [99]:
A - B

array([[0, 0, 0],
       [0, 0, 0]])

In [101]:
A * B # Element-wise multiply

array([[ 1,  4,  9],
       [16, 25, 36]])

In [102]:
A / B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
# 행렬 곱
result = np.dot(A,C) # dot product
result

array([[22, 28],
       [49, 64]])