In [1]:
import numpy as np

In [2]:
# 1차원 배열
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
type(arr1) # n-Dimensional array

numpy.ndarray

In [4]:
arr1.dtype #배열 내 데이터 의 타입

dtype('int64')

In [6]:
# 2차원 배열
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.shape # 모양, 배열의 형태 (각 차원의 크기) 2행 3열

(2, 3)

In [10]:
arr2.ndim # 배열의 차원 수 n-차원

2

In [11]:
a = np.zeros((2, 2)) #영행렬
a

array([[0., 0.],
       [0., 0.]])

In [12]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [13]:
a = np.eye(3) # Identitry matrix 항등행렬
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a = np.random.random((2, 2))
a

array([[0.31229117, 0.24765186],
       [0.55081267, 0.04382161]])

In [16]:
arr = np.random.randint(1, 100, size = (5, 5)) #random int
arr

array([[95, 40, 24, 88, 79],
       [13, 10, 38, 43, 29],
       [58, 82, 83,  1, 15],
       [30,  4, 71, 52, 36],
       [54, 37, 35, 58, 86]])

In [30]:
arr = np.random.random(10)
arr

array([0.57865063, 0.20873418, 0.84771963, 0.66272249, 0.86691712,
       0.48684215, 0.13160287, 0.62117085, 0.85359249, 0.79114805])

In [31]:
arr.sort()
arr

array([0.13160287, 0.20873418, 0.48684215, 0.57865063, 0.62117085,
       0.66272249, 0.79114805, 0.84771963, 0.85359249, 0.86691712])

In [32]:
arr[0]

0.13160286928745002

In [33]:
arr[2:5]

array([0.48684215, 0.57865063, 0.62117085])