In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4]) # 배열(Array)
v1

array([1, 2, 3, 4])

In [3]:
type(v1)

numpy.ndarray

In [6]:
# v1 array 안에 들어있는 데이터의 타입 출력
v1.dtype # d(ata)-type

dtype('int64')

In [10]:
# v2 = np.array([1,2,4.3,10])
# v2
v2 = np.array([1,2,4.3,'하이욤'])
v2

array(['1', '2', '4.3', '하이욤'], dtype='<U32')

In [11]:
v2.dtype

dtype('<U32')

In [12]:
# 각 차원의 아이템의 수
v1.shape

(4,)

In [13]:
v3 = np.array([[1,2,3],[4,5,6]])
v3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
v3.shape #2행 3열

(2, 3)

In [16]:
v1 = np.arange(5) # 'a'rray of 'range'
v1

array([0, 1, 2, 3, 4])

In [17]:
v2 = np.arange(5,15,2) # 'a'rray of 'range'
v2

array([ 5,  7,  9, 11, 13])

In [19]:
v3 = np.arange(1, 10, 2) ** 2
v3

array([ 1,  9, 25, 49, 81])

In [20]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
v2 = v1.reshape(2, 6) # 2행 6열로 만들어 줘 
v2
# v1.reshape(2, -1) -> 열 알아서 계산 "해줘"

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
v3 = v1.reshape(2, 6,order = 'F') # C & Fortran
v3

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [24]:
v1 = np.arange(12).reshape(4, -1) # 메서드 체이닝 (Method-chaining)
v1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
# np.ndarray의 사칙연산
v1 = np.arange(1, 5).reshape(2,2)
v1

array([[1, 2],
       [3, 4]])

In [26]:
np.max(v1)

4

In [27]:
np.min(v1)

1

In [28]:
np.mean(v1) 

2.5

In [29]:
np.std(v1) #표준편차

1.118033988749895

In [30]:
v1

array([[1, 2],
       [3, 4]])

In [31]:
np.add(v1, v1) # element-wise

array([[2, 4],
       [6, 8]])

In [32]:
np.subtract(v1, v1)

array([[0, 0],
       [0, 0]])

In [34]:
np.multiply(v1, v1)

array([[ 1,  4],
       [ 9, 16]])

In [35]:
np.dot(v1, v1) #행렬 곱 (dot-product)

array([[ 7, 10],
       [15, 22]])